### ISSUE TITLE
Support for 8Mhz boards?

### ISSUE THREAD

**Issue by raykamp** [TMRh20/TMRpcm#10]
Hey @TMRh20 , how can this library be modified to allow for Arduinos running at 8Mhz? 

I've looked into your code, but it's a bit confusing to follow the many variable names. I'm a FW guy and would be happy to help make this addition if you can point me in the right direction. 

Thanks for contributing this great library.
Any help is much appreciated. @simsalapim is interested in this as well. 

-Ray

**Comment by gamecompiler** [comment]
Thanks to d-a-v it works now without any problem. Just make sure that youd set the correct settings in the arduino IDE to match your oscillators clock.
