### ISSUE TITLE
Possibility of using PROGMEM for wav file

### ISSUE THREAD

**Issue by capescw** [TMRh20/TMRpcm#103]
I have created multiple WAV files, (8 bit unsigned) for use in a 'Blind Assist' program, and would prefer to use the PROGMEM capability to store them, rather than the SD card approach (plenty of room). I have begun with your basic sketch:
///////////////////////////////////////////////////////////////////////////////////

#include "TMRpcm.h"

TMRpcm tmrpcm;

const uint8_t spAPRIL[]  PROGMEM = {0x52, 0x49, 0x46, 0x46, 0xF8, 0x2C, 0x00, 0x00, 0x57, 0x41, 0x56, 0x45, 0x66, 0x6D, 0x74, 0x20, 0x10, 0x00, 0x00, 0x00, 0x01 0xFF, 0xF0, 0xFF, 0xEE, 0xFF, 0xEA, 0xFF, 0xF1, 0xFF, 0xEC, 0xFF, 0x04, 0x00, 0x06, 0x00, 0x13, 0x00, 0x11, 0x00, 0x19, 0x00, 0x13, 0x00, 0x17, 0x00, 0x13, 0x00, 0x14, 0x00, 0x18, 0x00, 0x18, 0x00, 0x24, 0x00, 0x27, 0x00, 0x2C, 0x00, 0x24, 0x00, 0x22, 0x00, 0x1A, 0x00, 0x19, 0x00, 0x14, 0x00, 0x13, 0x00, 0x13, 0x00, 0x19, 0x00, 0x19, 0x000};
//
// Truncated for space reasons, not directly usable
//

void setup()
{
  tmrpcm.speakerPin = 8;
  Serial.begin(9600);
}
void loop()
{ 
  tmrpcm.setVolume(6);
  tmrpcm.play uint8_t (spAPRIL);
  delay(10000);
}                          
///////////////////////////////////////////////
Obviously, doesn't work, so my question(s)

A - Is it even possible to do this
B - if so, what is the proper format for the line 'tmrpcm.play uint8_t (spAPRIL);'
C - failing this, is there an approach that I CAN use

I thank you profusely in advance

Bill C.
p.s I have tried the 'talkie' approach as well, but there are too many phrases missing, and none of the 'support' programs work 'out of the box'.

**Comment by TMRh20** [comment]
The library only supports storing the name of the wav file in program memory. 

See https://playground.arduino.cc/Code/PCMAudio/ for an example using progmem to store the sound data.
