### ISSUE TITLE
Conflict with Servo.h Library. Sketch does not compile.

### ISSUE THREAD

**Issue by antonsperling** [TMRh20/TMRpcm#105]
Arduino IDE 1.8.9 (On Ubuntu 19.04)
TMRpcm 1.1.0
Example Recording.ino
When i add the Standard Arduino Servo.h Library to the Recording.ino Example, the Sketch won't compile on Mega2560.

Error Message below:
> libraries/Servo/avr/Servo.cpp.o (symbol from plugin): In function `ServoCount':
(.text+0x0): multiple definition of `__vector_17'
libraries/TMRpcm/TMRpcm.cpp.o (symbol from plugin):(.text+0x0): first defined here
/home/asperling/.arduino15/packages/arduino/tools/avr-gcc/5.4.0-atmel3.6.1-arduino2/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld: Disabling relaxation: it will not work with multiple definitions
libraries/Servo/avr/Servo.cpp.o (symbol from plugin): In function `ServoCount':
(.text+0x0): multiple definition of `__vector_32'
libraries/TMRpcm/TMRpcm.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/Servo/avr/Servo.cpp.o (symbol from plugin): In function `ServoCount':
(.text+0x0): multiple definition of `__vector_42'
libraries/TMRpcm/TMRpcm.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/Servo/avr/Servo.cpp.o (symbol from plugin): In function `ServoCount':
(.text+0x0): multiple definition of `__vector_47'
libraries/TMRpcm/TMRpcm.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
exit status 1
Fehler beim Kompilieren für das Board Arduino/Genuino Mega or Mega 2560.

**Comment by TMRh20** [comment]
It’s just not compatible, both libraries are attempting to use the same interrupt vectors.
