### ISSUE TITLE
Implementation on stm32 boards

### ISSUE THREAD

**Issue by ujjwalk450** [TMRh20/TMRpcm#108]
The STM32F103C8T6 commonly known as "bluepill" is a common board that is being used with arduino ide and since its ARM based it has much more capabilities than the AVR based chips.

Future implementation is requested for ARM boards also.

**Comment by TMRh20** [comment]
Due to the design of TMRpcm, all future audio support will likely be added to the [AAAudio Library](https://github.com/TMRh20/AutoAnalogAudio) Currently supports AVR, ARM (Due), and I'm looking at other options.

**Comment by JoelMuhanguzi** [comment]
hello @TMRh20 were you able to provide support for ARM M4 boards like the STM32F4 blackpill?
