### ISSUE TITLE
Is there anyway to activate autoack in musicStreamerComplex?

### ISSUE THREAD

**Issue by alkuentrus** [TMRh20/TMRpcm#111]
Hi, is there anyway to activate Auto Acknowledge in musicStreamerComplex?

Im studding a project envolving  nrf24L01 for audio transmit, using your libraries, for protypes for remote zones in the mountains of madeira island (for helping people in distress or just for info). Right now, I  tested a prototype using improved modules and reached about 4 km range Fresnel Zone Clearance ! Right now I'm thinking of using TMRpcm to integrate the audio with SD Card (I'm preparing a function where the user records a message saying what he needs) to be sent after recording. However, we need to make sure that the message reaches its destination, thats why I thought of AutoACK.... What's your opinion?

**Comment by TMRh20** [comment]
You can try enabling auto ack in the radio settings, but this will reduce the max bit rate of the audio, and limit transmissions to a single device. In this situation I would rewrite the code entirely to use ack-payloads and establish a bidirectional comm channel.
