### ISSUE TITLE
'class TMRpcm' has no member named 'startRecording'

### ISSUE THREAD

**Issue by zzmbird** [TMRh20/TMRpcm#113]
I already modified the pcmConfig.h as was told(Uncomment #define buffSize 128 AND #define ENABLE_RECORDING in pcmConfig.h), but when running the "Recording" template, I still receive the same error...
it said :In function 'void loop()':
sketch_dec05aluyin:30:25: error: 'class TMRpcm' has no member named 'startRecording'

**Comment by zzmbird** [comment]
with ATmega328,please help,thanks.

**Comment by oveddan** [comment]
im using this on the nano 33 ble sense and have the same issue

**Comment by TMRh20** [comment]
This library is not compatible with nano 33 ble sense, basically only atmega328 based boards.

**Comment by Shubhayu-Das** [comment]
Check if you have put in the following code:
`#define ENABLE_RECORDING`
