### ISSUE TITLE
DISABLE_SPEAKER2

### ISSUE THREAD

**Issue by cebab54** [TMRh20/TMRpcm#124]
I am using a UNO R3 Board and this does not seem to do anything.  There is still a signal on Pin 10 as well as Pin 9.  I had assumed that Pin 10 would become 'silent' and unused when this OPTION was enabled?

**Comment by TMRh20** [comment]
Hmm, as long as you haven't enabled `#define USE_TIMER2` , it will prevent the timer output on pin10 from being enabled.

To verify, add the following code in your setup() section:
  ```
Serial.print("Test ");
Serial.println(TCCR1A,BIN);
```
With Speaker2 enabled: Test 10110010
With Speaker2 disabled: Test 10000010

If you get different results, try removing TMRpcm using Arduino library manager, then open your Arduino library folder (Documents->Arduino->Libraries) and delete any remaining TMRpcm folders. Then reinstall using the IDE.

**Comment by TMRh20** [comment]
Should probably add, you want to attempt to play an audio file before calling the above test code.

**Comment by cebab54** [comment]
Hi

Tried your test as suggested.  Result is same in both cases: With Speaker2 enabled or disabled:

Test result = 10110010 (in both states)

Deleted TMRpcn library files and re-installed using IDE (version 1.8.12) as suggested and result of test is exactly the same in both states.  So still not working.

Andrew

**Comment by TMRh20** [comment]
Ok, I have one more idea.
  
In the IDE, if you enable File->Preferences->Show Verbose Output During: Compilation , it should show something like this after compiling:  
` Using library TMRpcm at version 1.1 in folder: C:\Users\tmrh20\Documents\Arduino\libraries\TMRpcm `
  
Then of course just verify that you are editing the pcmConfig.h file in the folder where it is finding the TMRpcm library.

You can also call the following in your sketch to see if the define is being picked up at all:
```
  #if defined (DISABLE_SPEAKER2)
    Serial.println("SP2 Disabled");
  #endif
```

**Comment by cebab54** [comment]
Hi

Thanks.  The Define statements are working after adding the lines:

  #if defined (DISABLE_SPEAKER2)
    Serial.println("SP2 is Disabled");
  #endif

And not when commented out.

However, these statements do stop the audio.play() call to stop working.

When removed the clip plays correctly.

Another thing I have noticed is that the audio.play(“clipname.wav”,1) does not work. And the clip is not played at all, whereas using audio.play(“clipname.wav”) works correctly.  Is this a limitation of using the UNO board?

Andrew S Hudson

8 Kingswood Avenue,
Bromley BR2 0NY
m: +44 (0) 7836 349436

**Comment by cebab54** [comment]
Meant to say, although the define seems to be working as per tests and output to Serial Monitor, the Test output lines no longer work to show the Binary output AND there is still signal coming from Pin 10 even when the SPEAKER2 is disabled.


Andrew S Hudson


From: Andrew Hudson
Sent: 21 May 2020 20:30
To: TMRh20/TMRpcm <reply@reply.github.com>; TMRh20/TMRpcm <TMRpcm@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [TMRh20/TMRpcm] DISABLE_SPEAKER2 (#124)

Hi

Thanks.  The Define statements are working after adding the lines:

  #if defined (DISABLE_SPEAKER2)
    Serial.println("SP2 is Disabled");
  #endif

And not when commented out.

However, these statements do stop the audio.play() call to stop working.

When removed the clip plays correctly.

Another thing I have noticed is that the audio.play(“clipname.wav”,1) does not work. And the clip is not played at all, whereas using audio.play(“clipname.wav”) works correctly.  Is this a limitation of using the UNO board?

Andrew S Hudson

8 Kingswood Avenue,
Bromley BR2 0NY
m: +44 (0) 7836 349436

**Comment by cebab54** [comment]
Hi

There is something really weird going on.  I have uninstalled and reinstalled the TMRpcm Library now 4 times and every second time I run the IDE Compiler, there seems to be something overwritten that is stopping your Library from working correctly after that compile.

That said this time the compiler does not seem to be stopping the Library from working, but still there is signal on SPEAKER2, pin 10 despite SPEAKER2 test indicating it is OFF i.e.
20:49:56.790 -> Test 10000010
It is just a bit frustrating …. As I am sure you can appreciate …

Andrew S Hudson

From: Andrew Hudson
Sent: 21 May 2020 20:34
To: TMRh20/TMRpcm <reply@reply.github.com>; TMRh20/TMRpcm <TMRpcm@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [TMRh20/TMRpcm] DISABLE_SPEAKER2 (#124)

Meant to say, although the define seems to be working as per tests and output to Serial Monitor, the Test output lines no longer work to show the Binary output AND there is still signal coming from Pin 10 even when the SPEAKER2 is disabled.


Andrew S Hudson

From: Andrew Hudson
Sent: 21 May 2020 20:30
To: TMRh20/TMRpcm <reply@reply.github.com<mailto:reply@reply.github.com>>; TMRh20/TMRpcm <TMRpcm@noreply.github.com<mailto:TMRpcm@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [TMRh20/TMRpcm] DISABLE_SPEAKER2 (#124)

Hi

Thanks.  The Define statements are working after adding the lines:

  #if defined (DISABLE_SPEAKER2)
    Serial.println("SP2 is Disabled");
  #endif

And not when commented out.

However, these statements do stop the audio.play() call to stop working.

When removed the clip plays correctly.

Another thing I have noticed is that the audio.play(“clipname.wav”,1) does not work. And the clip is not played at all, whereas using audio.play(“clipname.wav”) works correctly.  Is this a limitation of using the UNO board?

Andrew S Hudson

**Comment by TMRh20** [comment]
Are you using the included examples or custom code? Any other libraries being used? If you are low on memory or there is a related issue like a buffer being overwritten etc. that is a common source of "weird" issues.

> audio.play(“clipname.wav”,1) does not work... Is this a limitation of using the UNO board?
Nope, the code is general to all boards.

**Comment by cebab54** [comment]
Hi

The code uses parts of the example code.  The RAM free is about 300

The Sketch is as follows:

#include <SD.h>
#include <TMRpcm.h>
#include <SPI.h>
#include <pcmConfig.h>
#include <BirdData.h>
#define SD_ChipSelectPin 4
#define LDR_ChipSelectPin 0
#define DIGI_LineoutSelectPin 9
#define AUDIO_Volume 4
#define EXT ".wav"
Sd2Card card;
TMRpcm audio;

const unsigned int DATA_SIZE = 11;
const boolean DEBUG = false;
BirdData data[DATA_SIZE];

// helper function to determine free ram at runtime
int freeRam () {
  extern int __heap_start, *__brkval;
  int v;
  return (int) &v - (__brkval == 0 ? (int) &__heap_start : (int) __brkval);
}

void(* resetFunc) (void) = 0; //declare reset function at address 0

void setup() {

  audio.speakerPin = DIGI_LineoutSelectPin;
  audio.setVolume(AUDIO_Volume);  // reset output volume
  Serial.begin(115200);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }

  //  #if defined (DISABLE_SPEAKER2)
  //    Serial.println("SP2 is Disabled");
  //  #endif
  //  #if defined (HANDLE_TAGS)
  //    Serial.println("HANDLE_TAGS is enabled");
  //  #endif

  Serial.print("Free Ram: ");
  Serial.println(freeRam()); Serial.flush();

  Serial.println("Initializing SD card...");
  // if (!card.init(SPI_HALF_SPEED, SD_ChipSelectPin)) {
  // check if an SD card is present and can be initialized:
  if (!SD.begin(SD_ChipSelectPin)) {
    Serial.println("SD Card initialization failed:");
    Serial.println("* is a card inserted?");
    Serial.println("* is your wiring correct?");
    Serial.println("* did you change the chipSelect pin to match your shield or module?");
    while (1);
  } else {
    Serial.print("Card type found is: ");
    switch (card.type()) {
      case SD_CARD_TYPE_SD1:
        Serial.println("SD1");
        break;
      case SD_CARD_TYPE_SD2:
        Serial.println("SD2");
        break;
      case SD_CARD_TYPE_SDHC:
        Serial.println("SDHC");
        break;
      default:
        Serial.println("Unknown");
    }
  }

  randomSeed(analogRead(LDR_ChipSelectPin)); // READ lIGHT LEVEL
}

void loop(void) {

  // Next determine the amount of light present to evaluate the day vs night settings.
  // We also build in some tolerance if the photocell is missing or broken so default to T
  // Day(D) or Twighlight(T) or Night(N)

  char when = 'T'; // set default to Twilight (Dusk/Dawn) not to be too intrusive at night

  int LPin = analogRead(LDR_ChipSelectPin);
  Serial.print("Photocell Reading (0-1023) is ");
  Serial.println(LPin); Serial.flush();

  // set random amount of wait time between birdcall clip loops
  unsigned long waitTime = 10000;
  if (LPin > 200) {
    when = 'D';
    // Daytime set 5 - 25 minutes
    waitTime = (random(300, 1500) * 1000);
    loadSoundsDay();
    // Load Daytime defined sound clips
  }
  else if (LPin > 30) {
    when = 'T';
    // Twilight or Dusk/Dawn set 30 - 60 minutes
    waitTime = (random(1800, 3600) * 1000);
    loadSoundsDawnDusk();
    // Load DawnDusk defined sound clips
  }
  else {
    when = 'N';
    // Night Time set 90 - 160 minutes
    waitTime = (random(5400, 9600) * 1000);
    loadSoundsNight();
    // Load Night Time defined sound clips
  }
  if (DEBUG) {
    // override to 10 seconds
    waitTime = 10000;
  }

  playRandomWavFile(when);
  int mins = int(waitTime / 60000);
  int secs = int((waitTime - (mins * 60000)) / 1000);
  Serial.print("Waiting for: ");
  Serial.print(mins);
  Serial.print(" min(s) ");
  Serial.print(secs);
  Serial.println(" sec{s)");
  Serial.println("------------------=-----------------");
  Serial.flush();
  delay(waitTime);

  Serial.print("Free Ram: ");
  Serial.println(freeRam()); Serial.flush();
}

void loadSoundsDay() {
 // (Wav name [mustbe an integer] excl extension, Daytime weighting, Nighttime weighting, Clip duration in seconds, minimum number of repeats)
  data[0].put(1, 18, 5, 5, 6);
  data[1].put(2, 12, 5, 21, 2);
  data[2].put(5, 12, 5, 1, 20);
  data[2].put(15, 5, 18, 83, 1);
  data[3].put(8, 12, 5, 13, 4);
  data[4].put(11, 18, 5, 13, 4);
  data[5].put(12, 9, 5, 32, 2);
  data[6].put(14, 14, 8, 10, 5);
  data[7].put(15, 15, 8, 83, 1);
  data[8].put(20, 10, 5, 86 , 1);
  data[9].put(21, 18, 5, 41, 2);
  data[10].put(22, 18, 5, 58, 3);
  return;
}

void loadSoundsDawnDusk() {
  // edit to load Dawn/Dusk sound clips, see next line and the details in files.xls
  // (Wav name [mustbe an integer] excl extension, Daytime Weghting, Nighttime weighting, Clip duration in seconds, minimum number of repeats)
  data[0].put(6, 5, 18, 14, 3);
  data[1].put(14, 18, 5, 10, 5);
  data[2].put(15, 5, 18, 83, 1);
  data[3].put(18, 5, 15, 65, 1);
  data[4].put(19, 7, 16, 89, 1);
  data[5].put(21, 18, 5, 41, 2);
  data[6].put(22, 5, 15, 58, 1);
  data[7].put(24, 5, 18, 32, 3);
  data[8].put(25, 5, 18, 65, 1);
  data[9].put(15, 5, 18, 83, 1);
  data[10].put(22, 5, 15, 58, 1);
  return;
}

void loadSoundsNight() {
  // edit to load Night time sound clips, see next line and the details in files.xls
  // (Wav name [mustbe an integer] excl extension, Daytime Weghting, Nighttime weighting, Clip duration in seconds, minimum number of repeats)
  data[0].put(6, 5, 18, 15, 3);
  data[1].put(18, 5, 15, 65, 2);
  data[2].put(19, 7, 16, 89, 1);
  data[3].put(23, 5, 18, 4, 4);
  data[4].put(24, 5, 18, 32, 2);
  data[5].put(25, 5, 18, 65, 1);
  data[6].put(6, 5, 18, 15, 4);
  data[7].put(18, 5, 15, 65, 1);
  data[8].put(19, 5, 18, 83, 1);
  data[9].put(24, 5, 18, 32, 3);
  data[10].put(25, 5, 18, 65, 1);
  return;
}

void playRandomWavFile(char when) {
  unsigned long maxTimesStart = 6;
  unsigned long rand = random(sumWeights(when));
  unsigned long runningWeights = 0;
  if (when == 'N') {
    // repeat less at night
    maxTimesStart = 2;
  }
  for (unsigned int w = 0; w < DATA_SIZE; w++) {
    runningWeights += data[w].getWeight(when);
    if (rand < runningWeights) {
      unsigned int maxTimes = (maxTimesStart + data[w].getMinTimes());
      playSound(data[w].getWavNr(), data[w].getDuration(), random(data[w].getMinTimes(), maxTimes), when);
      break;
    }
  }
  return;
}

long sumWeights(char when) {
  unsigned long weights = 0;
  for (unsigned int w = 0; w < DATA_SIZE; w++) {
    weights += data[w].getWeight(when);
  }
  return weights;
}

void playSound(int wavNr, long duration, long times, char when) {
  String wavFile = (String(wavNr) + EXT);  // set wavFile to wavNr (an Integer) to file number as a text String with .wav extension
  duration = duration * 1000;  // set length of clip as duration in Milliseconds
  Serial.print("Output volume is set to: ");
  Serial.println(AUDIO_Volume);
  Serial.flush();
  //
  // if using active speaker or amplifier use 100nf and 100K resistor in series from digital pin output connected to audio line input
  // -------||-------\/\/\/\/-----o Line in O---\/\/\/\/----GND
  //       100Nf     10K ohms                    1K ohms
  // Use pins 9 and 10 to feed separate line inputs to two channel amplifier, each channel wired as above
  // If pin 10 is used then make sure that SPEAKER2 is not disabled in pcmConfig.h in the TMRpcm Library
  //
  if (when != 'N') {  // if Night sounds required then delete this line 227 and lines 256-260 inclusive
    Serial.print("Playing ");
    Serial.print(wavFile);
    Serial.print(" ");
    Serial.print(times);
    Serial.println(" time(s); ");
    Serial.print("Sound clip duration is ");
    Serial.print(duration / 1000);
    Serial.println(" seconds.");
    Serial.print("Clip has been randomly selected from the '");
    Serial.print(when);
    Serial.println("' dataset.");
    Serial.flush();
    audio.loop(1);  // set loop play function on, this avoids the pop that can otherwise occur between the clips
    audio.play(wavFile.c_str());  // start loop playing
    for (unsigned long i = 0; i < times; i++) {
      // print progress of timing loop
      Serial.print("Looping - this clip is no. ");
      Serial.print(i + 1);
      Serial.print(" of ");
      Serial.println(times);
      Serial.flush();
      delay(duration); // wait for clip to finish before continuing
    }
    delay(100);
    audio.loop(0);  // set play loop function off
    Serial.println("Now finished current clip output.");
    Serial.flush();
    delay(100);
  } else {
    Serial.println("Night mode: No sounds to loop.");
    Serial.flush();
    delay(100);
  }
  return;
}

The only thing I get is a warning on compile that states as follows:


In file included from C:\Users\ashud\Documents\Arduino\libraries\arduino-bird-scarer\arduino-bird-scarer.ino:2:0:

C:\Users\ash\Documents\Arduino\libraries\TMRpcm/TMRpcm.h:31:7: note:   initializing argument 1 of 'void TMRpcm::play(char*)'

  void play(char* filename);

Thanks for your interest

Andrew S Hudson

**Comment by TMRh20** [comment]
As I said, the problem is going to be with your code. The library tests OK.

**Comment by cebab54** [comment]
Hi again

It has been a while since you sent the email below.  Many thanks for that feedback. The COVID Lockdown has become rather tedious until recently and I was persuaded to spend time decorating  …. Which kept me busy instead of focussing on the Arduino project. But my attention has turned back to the Arduino now.

One quick question.  Can the sound files for TMRpcm have ASCII based string names like “sound1.wav” or should they simply be named as “1.wav”?

Thanks

Andrew

Andrew S Hudson

**Comment by TMRh20** [comment]
Sound files can have ASCII strings names.

The stock SD library uses the Sd2Card class
