### ISSUE TITLE
Audio Amp for headphones

### ISSUE THREAD

**Issue by Sioreto** [TMRh20/TMRpcm#127]
Good morning,

I am currently looking for a good audio amplifier which can drive headphones (impedance not important) to be connected to the low pass filter required to use audio PWM. Do you have any suggestions (the voltage supply must be single and max 5 V)?
Thanks

**Comment by TMRh20** [comment]
The amplifier can be supplied with any voltage really, it just needs to share a common ground with the Arduino.  
  
I've usually just used an amplified speaker and similar so not sure what to suggest for driving headphones. If you take a look at the SimpleSDAudio library docs [here](https://www.hackerspace-ffm.de/wiki/index.php?title=SimpleSDAudio#Audio_amplifier_for_loudspeakers)  there is an easy circuit, but it might be a bit much for headphones. (That lib also uses PWM in a very similar way so I assume this should work well) Careful with your ears.
