### ISSUE TITLE
AUDIO Via PWM output on headphones

### ISSUE THREAD

**Issue by Sioreto** [TMRh20/TMRpcm#128]
Hi, 
I’m trying to use the library to play a WAV file from an SD card. Is it possible to send to a speaker/earphone directly the PWM signal (created by the code audio.play(“......wav”) or a low pass filter is required to act as a DAC?

**Comment by TMRh20** [comment]
Yes. If you are connecting directly, typically want to use a resistor
and/or capacitor with the speaker to limit current draw. See
https://www.hackerspace-ffm.de/wiki/images/thumb/SSDA_SimpleConnections.png/800px-SSDA_SimpleConnections.png

A filter may improve quality, but is not required.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
