### ISSUE TITLE
Using stereo mode with Ethernet Shield

### ISSUE THREAD

**Issue by Sioreto** [TMRh20/TMRpcm#131]
Good morning,
I am trying to obtain a stereo output using STEREO_OR_16BIT with an Arduino Uno and an Ethernet shield. Unfortunately, when I use the normal SD card module I am able to get the correct output at both pin 9 and 10, while if I use the shield I only perceive a loud high-pitched sound at both pins. Is there a way to obtain stereo output and using the Ethernet shield?
Thank you

**Comment by TMRh20** [comment]
Nope, the shield is hardwired to pin10 for SS/CS operations, so you would probably have to physically break that connection and modify the ethernet library to accommodate a different pin.

**Comment by Sioreto** [comment]
Thank you! And would it be possible to get stereo audio with the Mega and the Ethernet shield?

**Comment by TMRh20** [comment]
Should be possible
