### ISSUE TITLE
'TMRpcm' does not name a type; did you mean 'TMRpcm_h'?

### ISSUE THREAD

**Issue by mk12306** [TMRh20/TMRpcm#132]
'TMRpcm' does not name a type; did you mean 'TMRpcm_h'?
![图片](https://user-images.githubusercontent.com/50614823/88261628-3ff27a00-ccf9-11ea-83cd-e87851c56dad.png)

**Comment by TMRh20** [comment]
Are you using an included example? This typically means the .h file has not been included or something is way off.
