### ISSUE TITLE
atmega128

### ISSUE THREAD

**Issue by fadi0albaghdadi** [TMRh20/TMRpcm#134]
can i use this library with micro Atmega128

**Comment by TMRh20** [comment]
It should work but @8mhz sample rate needs to be lower, probably 12-16Khz

**Comment by fadi0albaghdadi** [comment]
Unfortunately, the library did not work



**************************************************************************************************************
In file included from c:\users\fadi\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino7\avr\include\avr\io.h:99:0,

                 from c:\users\fadi\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino7\avr\include\avr\pgmspace.h:90,

                 from C:\Program Files (x86)\Arduino\hardware\MegaCore-master\avr\cores\MCUdude_corefiles/Arduino.h:28,

                 from C:\Users\FADI\Documents\Arduino\libraries\TMRpcm/pcmConfig.h:20,

                 from C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:5:

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:20:27: error: 'ICIE1' was not declared in this scope

  const byte togByte = _BV(ICIE1); //Get the value for toggling the buffer interrupt on/off

                           ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:20:27: note: suggested alternative: 'TICIE1'

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:76:18: error: expected unqualified-id before 'volatile'

   volatile byte *TIMSK[] = {&TIMSK1,&TIMSK3};

                  ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:76:18: error: expected ')' before 'volatile'

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:76:18: error: expected ')' before 'volatile'

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:76:18: error: expected initializer before 'volatile'

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp: In member function 'void TMRpcm::stopPlayback()':

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:373:11: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

  *TIMSK[tt] &= ~(togByte | _BV(TOIE1));

           ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp: In member function 'void TMRpcm::pause()':

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:393:13: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

    *TIMSK[tt] |= ( _BV(ICIE1) | _BV(TOIE1) );

             ^

In file included from c:\users\fadi\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino7\avr\include\avr\io.h:99:0,

                 from c:\users\fadi\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino7\avr\include\avr\pgmspace.h:90,

                 from C:\Program Files (x86)\Arduino\hardware\MegaCore-master\avr\cores\MCUdude_corefiles/Arduino.h:28,

                 from C:\Users\FADI\Documents\Arduino\libraries\TMRpcm/pcmConfig.h:20,

                 from C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:5:

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:393:24: error: 'ICIE1' was not declared in this scope

    *TIMSK[tt] |= ( _BV(ICIE1) | _BV(TOIE1) );

                        ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:393:24: note: suggested alternative: 'TICIE1'

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:399:12: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

   *TIMSK[tt] &= ~( _BV(TOIE1) );

            ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp: In member function 'void TMRpcm::play(char*, long unsigned int)':

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:540:14: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

     *TIMSK[tt] = ( togByte | _BV(TOIE1) );

              ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp: In function 'void __vector_11()':

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:589:12: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

   *TIMSK[tt] &= ~togByte;

            ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:595:59: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

       if(bitRead(optionByte,3)){ sFile.seek(44); *TIMSK[tt] |= togByte; return;}

                                                           ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:596:16: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

       *TIMSK[tt] &= ~( togByte | _BV(TOIE1) );

                ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:608:13: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

    *TIMSK[tt] |= togByte;

             ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp: In member function 'void TMRpcm::disable()':

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:710:11: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

  *TIMSK[tt] &= ~( togByte | _BV(TOIE1) );

           ^

Multiple libraries were found for "SPI.h"
 Used: C:\Program
Multiple libraries were found for "SD.h"
 Used: C:\Program
 Not used: C:\Program
Multiple libraries were found for "TMRpcm.h"
 Used: C:\Users\FADI\Documents\Arduino\libraries\TMRpcm

**Comment by TMRh20** [comment]
Ahh, I was thinking atmega 168, I hear it helps to read things.

The ATmega devices all have such similar registers, you might be able to make some minor modifications to get it working. I don't know for sure, but a quick look at the datasheet indicates all the capabilities are there.

For example, ICIE1 on the 128 is TICIE1, the same functionality etc, just a different name, so going through TMRpcm.cpp and doing a find/replace would do the trick if this is the only register compatibility issue. Else it would require doing the same for any other registers with slightly different names.

I don't have any 128s myself to test with, else I would look at it closer.

**Comment by fadi0albaghdadi** [comment]
Unfortunately I tried a lot but couldn't solve the problem and it still didn't work

*******************************************************************

In file included from c:\users\fadi\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino7\avr\include\avr\io.h:99:0,

                 from c:\users\fadi\appdata\local\arduino15\packages\arduino\tools\avr-gcc\7.3.0-atmel3.6.1-arduino7\avr\include\avr\pgmspace.h:90,

                 from C:\Program Files (x86)\Arduino\hardware\MegaCore-master\avr\cores\MCUdude_corefiles/Arduino.h:28,

                 from C:\Users\FADI\Documents\Arduino\libraries\TMRpcm/pcmConfig.h:20,

                 from C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:5:

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:76:18: error: expected unqualified-id before 'volatile'

   volatile byte *TIMSK[] = {&TIMSK1,&TIMSK3};

                  ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:76:18: error: expected ')' before 'volatile'

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:76:18: error: expected ')' before 'volatile'

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:76:18: error: expected initializer before 'volatile'

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp: In member function 'void TMRpcm::stopPlayback()':

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:373:11: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

  *TIMSK[tt] &= ~(togByte | _BV(TOIE1));

           ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp: In member function 'void TMRpcm::pause()':

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:393:13: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

    *TIMSK[tt] |= ( _BV(TICIE1) | _BV(TOIE1) );

             ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:399:12: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

   *TIMSK[tt] &= ~( _BV(TOIE1) );

            ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp: In member function 'void TMRpcm::play(char*, long unsigned int)':

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:540:14: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

     *TIMSK[tt] = ( togByte | _BV(TOIE1) );

              ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp: In function 'void __vector_11()':

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:589:12: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

   *TIMSK[tt] &= ~togByte;

            ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:595:59: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

       if(bitRead(optionByte,3)){ sFile.seek(44); *TIMSK[tt] |= togByte; return;}

                                                           ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:596:16: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

       *TIMSK[tt] &= ~( togByte | _BV(TOIE1) );

                ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:608:13: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

    *TIMSK[tt] |= togByte;

             ^

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp: In member function 'void TMRpcm::disable()':

C:\Users\FADI\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:710:11: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

  *TIMSK[tt] &= ~( togByte | _BV(TOIE1) );

           ^

Multiple libraries were found for "SPI.h"
 Used: C:\Program
Multiple libraries were found for "SD.h"
 Used: C:\Program
 Not used: C:\Program
Multiple libraries were found for "TMRpcm.h"
 Used: C:\Users\FADI\Documents\Arduino\libraries\TMRpcm

**Comment by TMRh20** [comment]
https://gist.github.com/TMRh20/34dac78f4a532f0ccb51748f4f7ad86c

This can be copied into the TMRpcm library directory if you want to try it. It compiles, but I have no way to test it myself.

**Comment by fadi0albaghdadi** [comment]
ok thank u  so much i will try it
