### ISSUE TITLE
STM32

### ISSUE THREAD

**Issue by S144S** [TMRh20/TMRpcm#135]
Hi, how can we use this for stm32? 
by default this lib has error that dose not math with st architecture

**Comment by jackkum** [comment]
@saeed14473 
Use I2S + DAC

**Comment by saeed14473** [comment]
How? with this library or something else?

**Comment by jackkum** [comment]
https://github.com/afiskon/stm32-i2s-examples/tree/master/sdcard-wav-example

https://github.com/afiskon/stm32-i2s-examples/blob/master/sdcard-wav-example/Src/main.c

**Comment by Iftikhar-Omar** [comment]
> https://github.com/afiskon/stm32-i2s-examples/tree/master/sdcard-wav-example
> 
> https://github.com/afiskon/stm32-i2s-examples/blob/master/sdcard-wav-example/Src/main.c

Can you please help me with how to use that?
