### ISSUE TITLE
Servo Assistance please

### ISSUE THREAD

**Issue by RyanMako** [TMRh20/TMRpcm#140]
Hi guys!

I'm right now trying to use TMRpcm with the servos library and I'm running into issues. I'm using a MEGA2560, and when I try to combine my servo code with my audio library, I'm running into the issue of either the robot freezes up and doesn't want to move, or the audio file just doesn't want to play. supposedly I have to use some sort of second timer, according to a post made in 2014, but I have no idea how to set one of those up? can someone help me and point me in the correct direction? please, I'm a baby coder, its a school project due on the 20th. I thought I could combine stuff and it would be a happy marriage of code :(

https://1drv.ms/u/s!AjImrLgYf_MHh9c3BBsLy9J1HeDDow?e=LRhfsY

**Comment by TMRh20** [comment]
See the wiki. I don’t think the servo library is compatible though without some modifications to this library even if using timer2.
