### ISSUE TITLE
How do I change the playing speed of WAV during the playing?

### ISSUE THREAD

**Issue by Lewis224** [TMRh20/TMRpcm#144]
What I want to achieve is that , when the i < 120 , the Arduino will play the wav with 2x speed , and when the i > 160 , the Arduino will play the wav with 0.5x speed . Is anybody having ideas ? Any help would be appreciated.

**Comment by HubbleCommand** [comment]
I don't think there's any support for that. Easy solution would be to use something like Audacity to make different versions of your audio file played at different speeds. You could then use play(file, time) to start the different file at the same time that the previous one ended.
