### ISSUE TITLE
esp8266 and esp32 compability

### ISSUE THREAD

**Issue by AloneFe** [TMRh20/TMRpcm#145]
Hey is there any way to use the recording future on the ESP8266 or ESP32?
and is there any way to modify the .wav file? make it less noise when recording?

**Comment by TMRh20** [comment]
Esp32 is supported in the aaaudio library: https://github.com/TMRh20/AutoAnalogAudio

Using batteries or a cleaner power supply can reduce noise when recording.

**Comment by Iftikhar-Omar** [comment]
> Esp32 is supported in the aaaudio library: https://github.com/TMRh20/AutoAnalogAudio Using batteries or a cleaner power supply can reduce noise when recording.
> […](#)
> On Dec 22, 2020, at 5:02 PM, AloneFe ***@***.***> wrote: ﻿ Hey is there any way to use the recording future on the ESP8266 or ESP32? and is there any way to modify the .wav file? make it less noise when recording? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Please help with a more detailed guide. Most preferably step by step guide on how to use it with esp32.

**Comment by Theagainmen** [comment]
Would like to see this too, any updates?

**Comment by mahmou2001** [comment]
can you help me  i can't use the lib to record with esp32 with max9814

**Comment by TMRh20** [comment]
The ESP32 is not compatible with the TMRpcm library. I've tried to get it working with my other library, AutoAnalogAudio, but I don't believe the device is capable of recording without glitches. Playback may work ok, but recording seems to be a no-go.
