### ISSUE TITLE
wav file generation from ADS1115 issue 

### ISSUE THREAD

**Issue by ShaAgh** [TMRh20/TMRpcm#146]
hi there
i am building a voice recorder. i want to record a wav file with 16kHZ sampling rate and 16 bit rate resolution. due to the 10 bit limitation of arduino i am using an ADS1115 module to record in 16 bit rate through I2C protocol of arduino mega 2560. i tested my preamplifier microphone circuit and thankfully it has no problem. after connecting all parts , i wrote this sketch.

MY sketch: [wav generation.txt](https://github.com/TMRh20/TMRpcm/files/5740137/wav.generation.txt)

due to the sketch which is available in arduino TMRpcm library examples(File>examples>TMRpcm>xtraFeatures>wavGeneration), i expect MY sketch to create a WAV file with a couple of seconds duration  for me. but the result file is a sound of a low volume, single noisy beep with the duration of less than a second.

i do not know WHY and HOW. please please PLEASE! help me if you can.

**Comment by TMRh20** [comment]
If the main sound isn’t working it’s likely a problem with your part of the code involving the ADS1115, so not much I can help with.
