### ISSUE TITLE
Play 2 simultaneous audio clips from SPI Flash (Winbond W25Q128)

### ISSUE THREAD

**Issue by eugjr** [TMRh20/TMRpcm#147]
Hi, first of all, great library you've created.
It is possible to store and acess the audio files from a SPI Flash Chip, like Winbond W25Q128, instead of SD Card?

I'm trying to develop a board to play audio clips for a model train, it's important to be able to play 2 simultaneous songs (engine song and horn), but the problem is, as the space is very narrow, the sd card adapter wont fit on the model train, resulting the need to use winbond chips.

Thanks

**Comment by TMRh20** [comment]
Yeah it’s possible, but I have no experience with those chips. Just need to change the SD stuff to winbond code...

**Comment by Theagainmen** [comment]
Any updates on this? I would like to play 2+ audio clips simultaneously too!

**Comment by TMRh20** [comment]
ESP32 is not supported in TMRpcm. See the https://github.com/TMRh20/AutoAnalogAudio library
