### ISSUE TITLE
Long filename while recording

### ISSUE THREAD

**Issue by evgen2910** [TMRh20/TMRpcm#149]
**how long filename supported?**
whet try :
`audio.startRecording("abracadabra.wav", 16000, MicPin);// Старт записи`
dont write file on SD.

test.wav working normal. I`m try to use time from RTC as filename (time format - 010320211525 (date & time))

**Comment by TMRh20** [comment]
This has to do with fat sd card format and 8 character limit. Don’t think there is any way around it.

**Comment by evgen2910** [comment]
Thanks 👌
