### ISSUE TITLE
The library just won't work.

### ISSUE THREAD

**Issue by Nonsensible** [TMRh20/TMRpcm#153]
Every time, it gives the error message "/home/builder/opt/libraries/latest/tmrpcm_1_1_0/TMRpcm.cpp:20:27: error: 'ICIE1' was not declared in this scope"

**Comment by Nonsensible** [comment]
I don't know if this helps, but I am using a Nano 33 IoT

**Comment by Nonsensible** [comment]
I also have a normal Nano, so it's fine if it's just because its not compatible or something

**Comment by TMRh20** [comment]
Yeah only compatible with regular nano

**Comment by Nonsensible** [comment]
now it's saying collect2: error: ld returned 1 exit status

**Comment by Nonsensible** [comment]
nvm i got it to work thank you

**Comment by Nonsensible** [comment]
Wait nvm

**Comment by kausikp11** [comment]
Hi @Nonsensible how you made it work with Nano 33 IoT? Can you share the code if possible? or else let me know how?
