### ISSUE TITLE
Record finalize bug.

### ISSUE THREAD

**Issue by abelayer** [TMRh20/TMRpcm#160]
The finalizeWavTemplate function fails to set the file size in the header when using SD library.  The file is open with O_APPEND (as part of FILE_WRITE) which cause the seek to fail.   On line 1545 change FILE_WRITE  to O_READ | O_WRITE and it works.

**Comment by TMRh20** [comment]
Change added in https://github.com/TMRh20/TMRpcm/commit/32f16e02b196114a57b0a7262956d5ead475514d
