### ISSUE TITLE
Memory Chip

### ISSUE THREAD

**Issue by ljbeng** [TMRh20/TMRpcm#166]
Can the WAV information be put on an EEprom and played back for 1 or 2 sounds only?

**Comment by TMRh20** [comment]
Its not currently supported, but if the EEPROM is big and fast enough, I don't see why it wouldn't work. You would just have to change the SD code to read from the EEPROM chip instead.

**Comment by ljbeng** [comment]
Thanks! I will give that a try.  A 512kb EEPROM can hold approximately 4s of the 178kbps WAV file.  At a few bucks a chip, I could have 1 chip per sound easily.  The EEPROM talks I2C so I would need to test to see if the read speeds are fast enough.
