### ISSUE TITLE
Recording with SdFat library

### ISSUE THREAD

**Issue by yuhaszcam** [TMRh20/TMRpcm#167]
Is the recording still broken with the SdFat library? I saw another issue which was resolved in Oct '21 saying that the issue was fixed. Despite this, I still have not been able to record using the newest version of both the SdFat and TMRpcm library. Should I try using the version of SdFat from around that time?

**Comment by TMRh20** [comment]
It should be working, have you tested recording with the stock SD lib? What happens?
