### ISSUE TITLE
Qeustion - What is the output PWM frequency?

### ISSUE THREAD

**Issue by aerospacetgirl** [TMRh20/TMRpcm#168]
That's my question, what is the frequency PWM signal that this library used to play music. I don't own an oscilloscope and I couldn't figure it out from the code.

**Comment by TMRh20** [comment]
It varies dependent on the format of the input audio. It should be roughly 2x audio sample rate, so for a 16khz sample, the PWM frequency is 32khz. Setting audio.quality(0); reduces it to 16khz for a 16khz sample. The oversampling gets rid of some of the noise from lower quality samples (around 8khz etc)
