### ISSUE TITLE
Blank file recorded

### ISSUE THREAD

**Issue by rickyelqasem** [TMRh20/TMRpcm#172]
Any limitations using Arduino Nano A7 for the record pin?

**Comment by TMRh20** [comment]
Not that I know of, have you tested with A0?

**Comment by rickyelqasem** [comment]
so I have a button on A0 but that does seem to provide some feedback whereas A7 doesn't.  Also in your example code what is pinMode(12,OUTPUT) for? it talks about pin pairs, is that for the passthrough? I commented it out as I'm using pins 10-13 for the sd module.

**Comment by rickyelqasem** [comment]
I got it working in the end..
