### ISSUE TITLE
overdub Question from novice, not issue.

### ISSUE THREAD

**Issue by finncat62** [TMRh20/TMRpcm#177]
Hi, I'm using a teensy 4.1 with the Rev D audio shield(meaning that I have two sd cards). I am very novice with coding, just trying to use arduino for making effects pedals built into my instrument for music, I've already gotten every effect and the ui I want except for layering.

Main questions:
1) how do I sample audio from the shield line in, and then when playing it send to the boards build in lineout? 
     - On the documentation you just have it sending audio to a pin, as voltage going up and down. What pin would I configure that to, or is there a different way? I was looking on the PJRC store of the shield, but I wasn't seeing what I should do.
     - https://www.pjrc.com/store/teensy3_audio.html 
    - ie, just what would i set for **audio.speakerPin** ?
        - I want to send all of the audio through a mixer(?) or however they would all go to the board output pin, instead of sending to multiple pins(and even then, I don't know how I would get it to the audio shield output)
2) For overdub, is there a function that you made that ties the length of a recording to the length of a previous recording? If I want to do overdub, I was thinking of just making one recording, setting the length of every other recording after it, and using the multiple layers in your library. Is there a more effective way to do this, or just making a new layer saved in a different location and setting them all to play at once? 
     - For actually playing, it would be nice if the layers were all seperate so that I could also delete/remove layers one by one until the base, but it might be hard to code for me

3) Given that the 4.1 and Rev D have sd cards, can I use both of them at the same time? It would be perfect if i could save data from two pedals + each of their overdubs on each SD card, but I don't know how realistic that is (I want to have 4 tracks that I could record to, stop, start, and overdub on. If that isn't feasible, honestly however much the teensy 4.1 can give works) 

Final functionality:
I want to have multiple pedals that I can start or stop recording to, plus if I've stopped recording and have the max length for that recording I want to add layers on top of it(overdub).

more in-depth so that if you have any other thoughts/questions as to what I'm looking for:
  multiple buttons. Each button ->press once, that is the first recording, press again to stop recording, press again to add recording onto the current one(or just play a seperate file at the same time). If that new recording goes past the length of the first recording, then start a new layer, and play the one just finished plus the audio that is playing now. I also want the audio I'm currently playing to go out to the speaker, not saved into a buffer to only be played when the button is pressed.
  
  I want to do this for 4 separate pedals, each with as many over layers as possible, (I know that memory is limited). 
  
  would it be possible to, for instance, not have a maximum layers per pedal, but instead maximum save time in general? That way instead of (arbitrary) 4 layers max for each of the 4, use 2/3/4/7 layers respectively, or 2 massive layers that have the same length as the sum of the others time?
  
  How would you go about structuring this? Do you just keep track of the memory address and sd card? I'm not sure as to the capabilities for these in terms of saving .wav , so if an sd card has almost filled to where it can't do a whole nother layer but it has remainder space left over, could i do half the recording on one's remainder and half the recording on the other sd's remainder? I'm assuming that would be really complicated, I'm just curious as to what would be possible and then I'll figure it out as i get more familiar with coding. 

Thank you in advance for taking the time to respond to my quesitons. 
Mainly its just how to combine the signal from every layer and send to the audio shield, I can get it from there. Everything else is just if you have ideas for how I should go about the project.

Have a good day!

**Comment by TMRh20** [comment]
I hate to say it after your descriptive post, but the TMRpcm library
doesn't support the Teensy or its audio shield. Maybe see
https://www.pjrc.com/teensy/td_libs_Audio.html
