### ISSUE TITLE
Incompatible with megaavr architecture(s)

### ISSUE THREAD

**Issue by ADude0806** [TMRh20/TMRpcm#180]
I tried to play sound with this library but I can’t compile it for an Arduino Nano Every.
I get this error: WARNING: library TMRpcm-master claims to run on avr architecture(s) and may be incompatible with your current board which runs on megaavr architecture(s).

**Comment by ADude0806** [comment]
I don't know a lot about Arduino and libraries for them, but is this an issue that can/will be fixed?

**Comment by TMRh20** [comment]
Not unless somebody with some solid MCU programming skills and a device with MegaAVR arch decides to add support for it

**Comment by ADude0806** [comment]
Oh, thank you.
