### ISSUE TITLE
Any way to increase/decrease playback speed?

### ISSUE THREAD

**Issue by Zooyork01** [TMRh20/TMRpcm#181]
Hi, Thanks for the great library. I am about to start playing with it, but curious if I can somehow change the playback speed? I would like to change the speed based on a sensor value.

**Comment by TMRh20** [comment]
Heh https://github.com/TMRh20/TMRpcm/issues/169
Looks like this feature is kind of in demand, but I haven't had a chance to work on it.

Closing this issue as a duplicate.
