### ISSUE TITLE
MatLab Instalation

### ISSUE THREAD

**Issue by Fronk14** [TMRh20/TMRpcm#189]
I Seem to be unable to install it correctly as it doesn't appear in my library on MATLAB when I do "ListArduinoLibraries"

I put in in "C:\ProgramData\MATLAB\SupportPackages\R2023a\aIDE\portable\sketchbook\libraries", the same place as all my other libraries, I tried installing Arduino IDE and Adding the library in their sketchbook but still nothing.

**Comment by TMRh20** [comment]
This is not really related to the library, this is a Matlab/Arduino issue, so I would suggest you look elsewhere for support.

In any case, you can install via the Arduino Library Manager in the IDE, Matlab I'm not sure.
