### ISSUE TITLE
Stop recording when volume is low

### ISSUE THREAD

**Issue by DoubleF3lix** [TMRh20/TMRpcm#190]
Hello!

I found in another issue on this GitHub repository that you could access `ADCH` instead of `analogRead()` to get data from the microphone without causing noise. I also found that this value only updates when recording is in progress, however, the value it gives isn't consistent. At first I was checking if this value was below 70, and if so, then I stopped recording. However yesterday, that value needed to be about 50 to work, and today it's 110. 

Any idea why it's so inconsistent, and how I can fix that?
I tried using this to guess what the "normal" silence value is:
```cpp
    // This does not work. I do not know why.
    int silenceStartRecord = millis();

    // Get minimum volume
    audio.startRecording(silence_filename, 16000, A0);
    delay(500);
    while ((millis() - silenceStartRecord) < 1000) {
        int r = ADCH;
        Serial.println(r);
        if (r < silenceMin) silenceMin = r + 20;
    }
    audio.stopRecording(silence_filename);
    Serial.print("Silence min: ");
    Serial.println(silenceMin);
```
However, this would output 85-90, then it would shoot up to 110 in my actual recording tests (checked in `loop()`).

**Comment by TMRh20** [comment]
Its not quite that simple:
![image](https://github.com/TMRh20/TMRpcm/assets/2610460/69a2d143-a7a3-4a20-b7f6-da520b9d3675)

Audio comes in waves, so you typically need to find the peaks and troughs of the waveforms and do some math.
The audio library already samples from the ADCH register, so not sure if its really a good idea to do it while recording is happening.

In any case, hate to say it but, this is not really a software issue, but a programming issue, so I would have to refer you to the Arduino forums etc. for further info.

**Comment by DoubleF3lix** [comment]
Thank you!
