### ISSUE TITLE
Recording audio disables analog read

### ISSUE THREAD

**Issue by bradleywell** [TMRh20/TMRpcm#196]
I found that recording audio changes the ADMUX, ADCSRA, and ADCSRB registers, which prevents the analog pins from being able to read voltages. I was able to work around the issue by writing the registers back to what they were initially when I want to take a reading, but thought it might be worth bringing up as something that could be added into the recording function. I was using a Seeeduino Nano if it helps.

**Comment by TMRh20** [comment]
See Issue #101, I just fixed this the other day, I just haven't done a release yet.

You can install the library from here on GitHub by [downloading the ZIP](https://github.com/TMRh20/TMRpcm/archive/refs/heads/master.zip) and adding it via Arduino -> Sketch -> Include Library -> Add ZIP library
