### ISSUE TITLE
TMPpcm:1643 compiler warning

### ISSUE THREAD

**Issue by sonyhome** [TMRh20/TMRpcm#198]
Line 1643 in _TMRpcm::finalizeWavTemplate_ should cast to byte to remove compilation warnings:

`    seek(4); byte data[4] = {lowByte(fSize),highByte(fSize), (byte) (fSize >> 16),(byte) (fSize >> 24)};
`

**Comment by TMRh20** [comment]
Hmm, I guess I will take a look at all the compiler warnings today. I have some free time here during the holidays, so should clean this one up too. Thanks!
