### ISSUE TITLE
Support for UsbFat library

### ISSUE THREAD

**Issue by barcesat** [TMRh20/TMRpcm#20]
Hello @TMRh20 ,

I want to build a program that will seek audio file inside a USB DOK (DisK On Key) when it is inserted to the USB Host shield. (link: http://www.circuitsathome.com/products-page/arduino-shields/usb-host-shield-2-0-for-arduino )

I've saw that there's an example with a SD card (sdfat.ino).
I've fiddled a lot to get the USB Host Shield 2.0 library (link: https://github.com/felis/USB_Host_Shield_2.0)  to work and succeeded.

However I've found a simpler implementation of it in the UsbFat library: https://github.com/greiman/UsbFat

Can you help me connect between these two libraries (UsbFat & TMRpcm) and hopefully produca a similar example sketch?

**Comment by TMRh20** [comment]
From the looks of it, things would be treated very similarly to the standard SD or SDFat libraries, its just a matter of using the correct API to initialize and then read the files. There is probably not a lot I can do without access to the hardware, but if you run into specific problems, etc I may be able to assist.
