### ISSUE TITLE
using TMRpcm on Arduino Mega

### ISSUE THREAD

**Issue by danieltsz16** [TMRh20/TMRpcm#200]
Hi, I noticed that when using Arduino Mega Pin10 as output, when tmrpcm.play is executed, after the recording stops, arduino is stack. I tried to uncomment the disable_speaker2 but nothing happens

**Comment by TMRh20** [comment]
The pin pairs on Arduino Mega are as follows: Mega: 5-2, 6-7, 11-12, 46-45
Pin 10 cannot be used for output on a Mega.
