### ISSUE TITLE
Error with sdfat and recording

### ISSUE THREAD

**Issue by predomaquilare** [TMRh20/TMRpcm#202]
hello, i was trying to use the lib with my arduino nano, sd module and mic module
i followed the instructions in wiki about recording and using the sdfat lib, like uncomment some lines in pcmconfig
for the functions startrecording and stoprecording it solves, but now im with problems with the sdfat lib
the error image is right below
![image](https://github.com/TMRh20/TMRpcm/assets/104324993/269eb679-b011-4a96-b797-07ca6e9ab944)

by the way sorry for the bad english

**Comment by TMRh20** [comment]
Can you try opening TMRpcm.cpp and edit this line https://github.com/TMRh20/TMRpcm/blob/master/TMRpcm.cpp#L1853
Change to `sFile.truncate(fPosition());`

**Comment by TMRh20** [comment]
Thanks @predomaquilare for posting this issue, it has been fixed and a new release made which should be available in 24hrs.
