### ISSUE TITLE
Function not wokring 

### ISSUE THREAD

**Issue by benbreslov** [TMRh20/TMRpcm#204]
audio.startRecording and audio.stopRecording not recognized in library

/Users/benbreslov/Dropbox/MQP/Screen/FinalBaseCode/FinalBaseCode.ino: In function 'void startRecording()':
/Users/benbreslov/Dropbox/MQP/Screen/FinalBaseCode/FinalBaseCode.ino:38:9: error: 'class TMRpcm' has no member named 'startRecording'
   audio.startRecording("test.wav", 16000, A0);
         ^~~~~~~~~~~~~~
/Users/benbreslov/Dropbox/MQP/Screen/FinalBaseCode/FinalBaseCode.ino: In function 'void stopRecording()':
/Users/benbreslov/Dropbox/MQP/Screen/FinalBaseCode/FinalBaseCode.ino:43:9: error: 'class TMRpcm' has no member named 'stopRecording'
   audio.stopRecording("testTMR.wav");
         ^~~~~~~~~~~~~
Multiple libraries were found for "SD.h"
  Used: /Users/benbreslov/Documents/Arduino/libraries/SD
  Not used: /Users/benbreslov/Library/Arduino15/libraries/SD
exit status 1

Compilation error: 'class TMRpcm' has no member named 'startRecording'

**Comment by TMRh20** [comment]
https://github.com/TMRh20/TMRpcm/wiki/Advanced-Features#recording-audio
