### ISSUE TITLE
demo music request in wiki

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [TMRh20/TMRpcm#21]
Hi, it would be great advertising for the library if you posted a section in your wiki with links to demo music coming from an Arduino running your code. Ex: post a youtube video (better), or even an mp3 download (ok), of various songs (with vocals) playing, being produced by an Arduino. I'd like to know how well this library can reproduce regular mp3 tracks with vocals, without having to build the circuit and load the code (though I will _eventually_ get around to this).

Thanks!
Looks like a great lib.

**Comment by TMRh20** [comment]
Thanks for the input. Theres lots of examples on youtube etc, so this would not be too dificult. For now, here are some potential links to use. Feel free to add any more.

http://www.instructables.com/id/Playing-Wave-file-using-arduino/

http://timewitharduino.blogspot.com/2013_05_01_archive.html

http://www.instructables.com/id/Hockey-Goal-Horn/

https://www.youtube.com/watch?v=zaoVO1optkA

https://www.youtube.com/watch?v=XgKXwTjAgXM


Technically the library will only play .wav files, mp3 is too much to handle.

**Comment by gamecompiler** [comment]
I will record some of them next weekend. Shouldnt need that much time.
Perfect chance to use my new audio breadboard adapter 😈

**Comment by gamecompiler** [comment]
Coud you please give me push access? Ive got some demo music ready. I also recorded it from the arduino to give people a demo of what Arduino pcm sounds like.

**Comment by gamecompiler** [comment]
Music has been added, closing now.
