### ISSUE TITLE
Leonardo Compatibility

### ISSUE THREAD

**Issue by mdl00** [TMRh20/TMRpcm#210]
It seems like the Leonardo board is excluded from the compatibility list. Is there a reason for that? Since Timer1 controls PWM on pins 9 and 10 I'm not sure why this wouldn't work when a speaker is connected to one of these. If there is a limitation, is there anything in the library that could be tweaked so that it works with Leonardo?

**Comment by TMRh20** [comment]
It should work on the Leonardo
