### ISSUE TITLE
Refine volume steps 0-4 to 0-30 steps.

### ISSUE THREAD

**Issue by twilight102** [TMRh20/TMRpcm#211]
Good day, 
I am very happy with your made library.  
But I have a wish; The volume increments can be made in smaller increments.  
So from 0-4 steps to 0-30 steps with the same end volume as 4. 
I ask this because I want a .wav file to slowly increase in volume. 
If possible then I will be very satisfied 

greetings Ebro de Wit
translated

**Comment by TMRh20** [comment]
Hey there, unfortunately this is not likely something I would consider adding to the library. Volume control is kind of an advanced feature and probably requires quite a few changes to implement. Thx for the suggestion though.
