### ISSUE TITLE
Library conflict error 

### ISSUE THREAD

**Issue by AllwinAristo** [TMRh20/TMRpcm#213]
I tried to create a model computer with tvout library and tmrpcm for TV command output and audio playback. But, the compiler gives this error: (both libraries are up to date)

libraries\TMRpcm-1.3.6\TMRpcm.cpp.o (symbol from plugin): In function optionByte':

(.text+0x0): multiple definition of vector_20'

libraries\arduino-tvout-1.0.2\video_gen.cpp.o (symbol from plugin): (.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1

Error compiling for board Arduino/Genuino Micro.

This report would have more information with "Show verbose output during compilation" option enabled in File -> Preferences.

**Comment by TMRh20** [comment]
Sounds like a cool project.

Unfortunately, the TMRpcm library and TVOut libraries both use the same timers, so won't play together nicely.

If you see the [Advanced Features in the Wiki](https://github.com/TMRh20/TMRpcm/wiki/Advanced-Features), there is an option to use Timer2 for TMRpcm. I'm not sure if this will work, but is something to try.
