### ISSUE TITLE
compatibility with Arudino Nano Every?

### ISSUE THREAD

**Issue by AdamWysokinski** [TMRh20/TMRpcm#215]
This [table](https://docs.arduino.cc/libraries/tmrpcm/#Compatibility) shows that TMRpcm is compatible with Nano Every, but I get compilation error indicating incompatibility. Could anyone clarify the issue?

**Comment by TMRh20** [comment]
That table is wrong. Not sure how it gets generated, but TMRpcm is only compatible with the ones listed under AVR.

**Comment by AdamWysokinski** [comment]
Thanks!
