### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by DangerousWho** [TMRh20/TMRpcm#25]
I

For my final project i'm thinking about making a small sequencer out of squares with arduino but i'm not sure how to start. I just started out with arduino and i'm still learning.

Is it possible do determine and modify the samples bpm (resample them to fit the bpm) and loop a sample while that sample's switch is pressed?

**Comment by TMRh20** [comment]
I don't think so. If you are talking about analyzing the audio to get the BPM of the sound itself, this is well beyond the general capabilities of AVR devices. You would need a much more advanced audio lib and MCU.
