### ISSUE TITLE
Could you add this library to Arduino's Library Manager?

### ISSUE THREAD

**Issue by q2dg** [TMRh20/TMRpcm#28]
This would give more visibility to your fantastic job. 
Thanks!

P.D: Hope it helps... https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by TMRh20** [comment]
Its on the list!

**Comment by TMRh20** [comment]
Library updated and request made. If correct, it should show up as soon as they process the request.

**Comment by q2dg** [comment]
Thanks a lot!!
