### ISSUE TITLE
Support For ATmega32U4

### ISSUE THREAD

**Issue by rub8n** [TMRh20/TMRpcm#29]
Hello!

Looking at the Wiki it seems the library doesn't currently support ATmega32U4 devices such as the Arduino Micro, correct? If not, do you plan to support it? 

Thanks!

**Comment by TMRh20** [comment]
Hehe, well 'supported' is a rough term, but code is included to support the 32U4 devices via timer1 and/or timer3. (it should work)

**Comment by RuRios** [comment]
Cool. I ordered a few Micro's and i'll check it out once they arrive.

**Comment by gamecompiler** [comment]
Works. Closing now.
