### ISSUE TITLE
Playing From Onboard Flash

### ISSUE THREAD

**Issue by eboston** [TMRh20/TMRpcm#34]
Has there been any discussion about the ability to play a file that is saved in the onboard flash memory instead of an SD card?  I have a project that I am working on where I want to play a background sound.  The WAV file is less than 2K and the sketch to play using the SD card plus the other things I am having it do is about 16K so there is space for it all.  I would like to be able to put this all together without having to put a SD card on.

**Comment by TMRh20** [comment]
Not really as far as I am aware. 

In theory it would be basically the same as with SD, you would probably just need to change the SD functions to handle reading from flash instead of SD.
