### ISSUE TITLE
play song one after another in a loop

### ISSUE THREAD

**Issue by simon11111** [TMRh20/TMRpcm#44]
hi master

i have tried to put wav.play("music1.wav"); and wav.play("music2.wav"); in the setup()
it worked
but when I placed these files into the loop
it cannot play both files   it only played one 

is there a way to play my music one after another without pressing any button?

Thanks a lot.

**Comment by TMRh20** [comment]
Something like this? See the progmem example maybe too

```
#include <SD.h>
#include <SPI.h>
#include <TMRpcm.h>

#define SD_ChipSelectPin 4

TMRpcm wav;

char *wavs[] = {"music1.wav", "music2.wav", "music3.wav"};
uint8_t counter;

void setup() {
  wav.speakerPin = 9;
  Serial.begin(9600);
  SD.begin(SD_ChipSelectPin);
}

void loop() {
  if (!wav.isPlaying()) {
    wav.play(wavs[counter]);
    counter++;
    ++counter %= 3;
  }
}
```

**Comment by simon11111** [comment]
Thanks a lot! It worked! :)

**Comment by Kilsan7** [comment]
You're genius!!!

**Comment by gamecompiler** [comment]
Seems solved :)
