### ISSUE TITLE
Starting Music and Pwm Signal Down

### ISSUE THREAD

**Issue by fearles577** [TMRh20/TMRpcm#52]
Hi, 

im control arduino with RC car transmitter. receiver signal pins connected A0, A1, A2.
İm read signal 1000-2000 and mapping -255/255. 0 (Zero) center position. 

Speaker connected 9. Pin on Arduino Uno

İm starting arduino, transmitter at center position and serial print analog pins 0 value. 
İm doing button up Serial print 255 and button down Serial print -255.
No problem so far...
Again transmitter center position, Serial Print 
A0: 0
A1: 0
A2: 0

Button down
A0: -255
A1: -255
A2: -255

Button Up
A0: 255
A1: 255
A2: 255

only start playing wav and later 

A0: -255
A1: -255
A2: -255

Music continues playing, Button down
A0: -255
A1: -255
A2: -255

Music continues playing, Button up

A0: -130
A1: -130
A2: -130

And stop play music.
returns to normal
A0: 0
A1: 0
A2: 0

I would be very happy if you help

Thanks

**Comment by TMRh20** [comment]
I'm not sure I understand the problem? Can you post your code, along with a more detailed explanation of what is happening?

**Comment by gamecompiler** [comment]
Im sure he didnt even read your answer TMRh20. fearless577, please reopen this issue and post your code here if you read this.
