### ISSUE TITLE
It conflict with other communication and stop my controller.

### ISSUE THREAD

**Issue by Joypacharya** [TMRh20/TMRpcm#55]
Actually i am working on timer based music system.At that time RTC places at I2C pin and SD card at SPI pin. RTC works very well until start Song.After started this system my controller has been stopped.
So, can i use timer2 in my TMRpcm library? 
With the guidance of yours i will do it completely.Please help me.

**Comment by gamecompiler** [comment]
What RTC lib did you use? Or what generally did you use? Id built myself a alarm clock without problems using rtclib.

If this issue is solved please close it.
