### ISSUE TITLE
Possible to set different PWM frequency for playback

### ISSUE THREAD

**Issue by Comiter** [TMRh20/TMRpcm#57]
Hi,
do anyone know if it possible to alter the PWM frequency on the Audio Out pin?
I would be happy to exchange resolution for increased PWM frequency (to be able to remove the switching noise from the playback).

**Comment by gamecompiler** [comment]
Id got no switching noise, but that wouldnt be the correct solution to fix "switching noise".
Could you please record you audio? Than i may be able to help you.

If we change the PWM frequency that wouldnt have any effect.
Only if we change the overall sampling rate - INCLUDING the PWM frequency.
(Please correct me if im wrong) 

What you can do to increase audio quality is to build a low pass filter. Just google for it and you audio will be 100% better (Not hifi, but its quite nice :D)

**Comment by gamecompiler** [comment]
Did you try the low pass filter?
Please reopen issue if you need help.
