### ISSUE TITLE
Filename mismatching

### ISSUE THREAD

**Issue by torejx** [TMRh20/TMRpcm#59]
Hi guys,

I have a strange problem. My SD (formatted as FAT16) has 4 .wav called 01.wav, ... 04.wav.

If I try to play 01, the 02.wav starts, If I try 03, nothing starts. How could it be possible?

Other question, in one case the audio is truncated, but the original file is not. Why?

Thanks!

**Comment by gamecompiler** [comment]
First, please show us your code.

**Comment by torejx** [comment]
Sorry, I tried to format the SD as FAT32 (it was FAT16) and it works :|
