### ISSUE TITLE
clicking sound when playing

### ISSUE THREAD

**Issue by yonoodle** [TMRh20/TMRpcm#62]
## Dear contributor, 

thank you for created such good lib,  but i found some clicking sound exist during playing , 
it ticks 1 time per second , periodically (about 58 bpm )   ,the ticking sound exist only when playing , it stop as the file stop playing.   what could this issue related to?

i used arduino atmega328P 16MHz nano module , powering by computer's USB hub.

the audio file is made as the instruction indicated  ,  recording a constant pitch singing note of at least 5 second.
and i tried other files , the clicking per second still exists.

the code: 

```

#include <SD.h>                      
#include <TMRpcm.h>           
#include <SPI.h>

TMRpcm tmrpcm;
void setup() {
if (!SD.begin(SD_ChipSelectPin)) {return;}
tmrpcm.setVolume(5);
tmrpcm.play("filename"); 
}
void loop() {
}

```

best regards

yonoodle

**Comment by gamecompiler** [comment]
How did you interface with the DAC ? Did you try to add a low pass? (I always do, or sometimes a RC-filter, please try adding a filter and post back if you eliminate the DC)

**Comment by gamecompiler** [comment]
Very noisy because of my crap soundcard (maybe also overloaded):
https://raw.githubusercontent.com/TMRh20/TMRpcm/master/audio_samples/texasradiofish_-_Slow_Cooker/recorded.ogg

Thats how the sound sounds like.

**Comment by yonoodle** [comment]
what cut off frequency do you recommend?

**Comment by gamecompiler** [comment]
I do not remember when id have to enter a cut off frequency Oo! Im sorry.
Did you solved your clicking noise?

Thanks in advance,
gamecompiler
