### ISSUE TITLE
is it possible to add the F() progmem feature in the future?

### ISSUE THREAD

**Issue by yonoodle** [TMRh20/TMRpcm#63]
Dear all ,

i know there's an example file for using progmem in the example folder ,
but is it possible to add the feature to simply use F()  just like    tmrpcm.play(F("filename_in_flash")    ?

it will be much easier to use , isn't it?

i tried but the lib didn't support the FlashStringHelper ... returned an compiling error
(sorry it is far beyond my ability to make the contribution...)

**Comment by TMRh20** [comment]
Added in https://github.com/TMRh20/TMRpcm/commit/9d312f68bda08074147abacea472bcd0eab938e6
