### ISSUE TITLE
Recording to SD card in real time

### ISSUE THREAD

**Issue by grzegorz-uniti** [TMRh20/TMRpcm#65]
Hello,
it is possible to create function that record on SD Card *.wav file in real time?
Now it's limited to buffer and it's not continuous - i mean saving to SD.

Best regards!

**Comment by grzegorz-uniti** [comment]
Sorry, I has analyzed code and I see now it's should work, but if I recording *.wav larger then 10 minutes length the file is broken.

**Comment by gamecompiler** [comment]
Please show us your code. Otherwise we cant help.

**Comment by grzegorz-uniti** [comment]
Thank's for replay!
I fixed bug, it was in my code, not TMRpcm.

Thank's to coder's for this great lib!
