### ISSUE TITLE
Is it possible to use it with MegaCore (ATmega128) ?

### ISSUE THREAD

**Issue by curtzan** [TMRh20/TMRpcm#66]
Try to use pin13 (oc1a) for speaker, but it is not compile.  It has many differend errors like 

C:\Users\Admin\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:607:13: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript
    *TIMSK[tt] |= togByte;

Full list of errors https://yadi.sk/i/sGMCyHQ33J3WM3
Is it possible to use TMRpcm with MegaCore (ATmega128) ? How?

**Comment by gamecompiler** [comment]
Please give us your full code and version number of your IDE.

**Comment by fadi0albaghdadi** [comment]
did you found result for this error

**Comment by curtzan** [comment]
No, i did`nt.15.06.2020, 23:34, "fadi0albaghdadi" <notifications@github.com>:
did you found result for this error
