### ISSUE TITLE
High Pitch Noise when fading RGBs

### ISSUE THREAD

**Issue by tcox8** [TMRh20/TMRpcm#70]
I have tried everything but when I have RGBs connected to PWM (I tried multiple pins) it causes a high pitch noise on the speaker. I have a RC filter in place that helps slightly but the noise is still annoying! Any ideas?

**Comment by gamecompiler** [comment]
Nope, i dont.  Youll need to check your circuit which frequency youll have to pass or not. You cant just easilly add an RC filter. You could build a bandpass or sth similiar. Or try another pwm frequency.

Heres an example of what playing audio sounds like when im letting my arduino play some music.

https://raw.githubusercontent.com/TMRh20/TMRpcm/master/audio_samples/Fireproof_Babies_-_Baked_Chicken_Heat/recorded.ogg
