### ISSUE TITLE
Circuit Diagram for Complementary Output on 1 Speaker.

### ISSUE THREAD

**Issue by xiaoxiao921** [TMRh20/TMRpcm#78]
Hi, i'd like to send 2 different sound on the same speaker at the same time. The problem is that i'm failing to understand how I should wire the input on the speaker. Do I need to amplify both of the input separately, using two separated input on an amp ? Or can I just wire both of the input on the same Amp's input and plug the amp's output on the + Input of my speaker. Right now my setup for a single sound is the speaker pin of the arduino plugged to Input 1 of my L298N IC Amp. And the Arduino GND plugged into the Input 2 of the Amp. (i don't even know if its right but its working atleast)

Sorry if this question seems really dumb but i don't really know what to do

**Comment by TMRh20** [comment]
Depending on the amplifier, you may be able to use the 2nd speaker pin to input 2 of the amp. Else each channel needs to be amplified separately and then fed to a speaker.
