### ISSUE TITLE
Get current time?

### ISSUE THREAD

**Issue by vin-ni** [TMRh20/TMRpcm#81]
Is it possible to get the current time value?

Thanks!

**Comment by TMRh20** [comment]
Nope, that would have to be done separately.

**Comment by vin-ni** [comment]
Ok,
can you give me a hint on how to achieve it? I'm really new to this.
I looked into the `pcmRF.h` but couldn't find out how to access `TIMER1`. Would that be the right way to go? Or should I start another timer that always runs when audio is playing

**Comment by TMRh20** [comment]
Probably easiest to set another timer to run slowly and count the seconds/time manually

**Comment by vin-ni** [comment]
How exactly would you use mili()? I ended up using an additional timer library.
