### ISSUE TITLE
read text file from sd  card before playing wav file

### ISSUE THREAD

**Issue by butlerps** [TMRh20/TMRpcm#84]
Hi,
I have a wav file 1.wav and a text file 1.txt, the latter has one line which is the length in seconds of the wav file.
I want to read the text file, get the length of the audio track then play the wav file with the correct time delay, this way if I change track 1 I don't have to re-program the nano.
The issue is, I can't read from the SD card whilst TMRpcm is included.  Has anyone else experienced this and got it working?  

`
#include <SD.h>                      // need to include the SD library
#define SD_ChipSelectPin 4  //using digital pin 4 on arduino nano 328
#include <TMRpcm.h>           //  also need to include this library...
#include <SPI.h>

TMRpcm tmrpcm;   // create an object for use in this sketch
 
void setup(){
int speaker = 9;
int duration = 0;
  // Open serial communications and wait for port to open:
  Serial.begin(9600);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }
  Serial.print("Initializing SD card...");

  if (!SD.begin(SD_ChipSelectPin)) {
    Serial.println("initialization failed!");
    while (1);
  }
  Serial.println("initialization done.");

  pinMode(speaker, OUTPUT);
  digitalWrite(speaker, LOW);
  tmrpcm.speakerPin = speaker; //11 on Mega, 9 on Uno, Nano, etc
  tmrpcm.volume(1);
  tmrpcm.quality(1);

  File myFile = SD.open("1.txt");
      if (myFile) {
        Serial.println("1.txt");
        while (myFile.available()) {
          duration = myFile.parseInt();
          Serial.print(duration);
        }// close the file:
        myFile.close();
      } else {
      // if the file didn't open, print an error:
      Serial.println("error opening 1.txt");
      }
}
 
void loop(){      
      tmrpcm.play("1.wav");
      delay(duration * 1000);
     }
  
`

**Comment by jonathanrjpereira** [comment]
Are you getting any error messages?
