### ISSUE TITLE
Need guidance to run this on ESP32.

### ISSUE THREAD

**Issue by ajinkyaw** [TMRh20/TMRpcm#85]
Hi . I want to execute the recording sketch on esp32.
Please guide me what changes needs to be done in the libs.

**Comment by TMRh20** [comment]
It would have to be completely rewritten.

**Comment by d-a-v** [comment]
To play on esp8266 or esp32: [esp8266/esp32/play](https://github.com/earlephilhower/ESP8266Audio)
To record on esp32: [esp32/record](https://github.com/MhageGH/esp32_SoundRecorder)

**Comment by d-a-v** [comment]
https://github.com/earlephilhower/ESP8266Audio#software-i2s-delta-sigma-dac-ie-playing-music-with-a-single-transistor-and-speaker

**Comment by tablatronix** [comment]
Thanks, looks like it uses i2s or dma pin only, hmm
