### ISSUE TITLE
Volume too low

### ISSUE THREAD

**Issue by ifeghali** [TMRh20/TMRpcm#87]
Hello 

I’m using this module as an audio amplifier 

https://goo.gl/images/ZK47qJ

But volume output from TMRpcm is too low. I can call setVolume to a maximum of 4, after that no sound can be heard. 

Exact some circuit and setup the tone() function produces audio much much louder. Any tips ?

**Comment by ecoulson** [comment]
Same issue here, did you find anything?

**Comment by ifeghali** [comment]
Unfortunately not.

**Comment by periode** [comment]
Hey, I'm having the same problem.

@ifeghali  Did you try with another amplifier module?

**Comment by ifeghali** [comment]
Yes I did, same problem. I gave up eventually, not using any circuit with
sound capabilities at the moment.

Em ter, 28 de abr de 2020 às 13:07, Pierre Depaz <notifications@github.com>
escreveu:

**Comment by periode** [comment]
Hey @ifeghali 

I had the same issue and I changed the power supply. The Arduino Nano I'm using supplies around 4V and by using a 9V battery or a step up voltage converter to power the LM386 amp, you notice a significant difference (the LM386 can handle up to 12V).
