### ISSUE TITLE
ATmega32 problem

### ISSUE THREAD

**Issue by Master811129** [TMRh20/TMRpcm#88]
couldn't compile it on an ATMEGA32

this is the errors messages:

``Arduino: 1.8.5 (Windows 10), Board: "ATmega32, Standard, 2.7v, Disabled (default), 16 MHz external"

D:\Arduino\arduino-builder -dump-prefs -logger=machine -hardware D:\Arduino\hardware -hardware C:\Users\Master\AppData\Local\Arduino15\packages -hardware C:\Users\Master\Documents\Arduino\hardware -tools D:\Arduino\tools-builder -tools D:\Arduino\hardware\tools\avr -tools C:\Users\Master\AppData\Local\Arduino15\packages -built-in-libraries D:\Arduino\libraries -libraries C:\Users\Master\Documents\Arduino\libraries -fqbn=MightyCore:avr:32:pinout=standard,BOD=2v7,LTO=Os,clock=16MHz_external -ide-version=10805 -build-path C:\Users\Master\AppData\Local\Temp\arduino_build_706859 -warnings=none -build-cache C:\Users\Master\AppData\Local\Temp\arduino_cache_534197 -prefs=build.warn_data_percentage=75 -verbose C:\Users\Master\Documents\Arduino\libraries\TMRpcm\examples\music\music.ino
D:\Arduino\arduino-builder -compile -logger=machine -hardware D:\Arduino\hardware -hardware C:\Users\Master\AppData\Local\Arduino15\packages -hardware C:\Users\Master\Documents\Arduino\hardware -tools D:\Arduino\tools-builder -tools D:\Arduino\hardware\tools\avr -tools C:\Users\Master\AppData\Local\Arduino15\packages -built-in-libraries D:\Arduino\libraries -libraries C:\Users\Master\Documents\Arduino\libraries -fqbn=MightyCore:avr:32:pinout=standard,BOD=2v7,LTO=Os,clock=16MHz_external -ide-version=10805 -build-path C:\Users\Master\AppData\Local\Temp\arduino_build_706859 -warnings=none -build-cache C:\Users\Master\AppData\Local\Temp\arduino_cache_534197 -prefs=build.warn_data_percentage=75 -verbose C:\Users\Master\Documents\Arduino\libraries\TMRpcm\examples\music\music.ino
Using board '32' from platform in folder: C:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1
Using core 'MCUdude_corefiles' from platform in folder: C:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1
Detecting libraries used...
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "C:\Users\Master\AppData\Local\Temp\arduino_build_706859\sketch\music.ino.cpp" -o "nul"
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "C:\Users\Master\AppData\Local\Temp\arduino_build_706859\sketch\music.ino.cpp" -o "nul"
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "C:\Users\Master\AppData\Local\Temp\arduino_build_706859\sketch\music.ino.cpp" -o "nul"
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src" "C:\Users\Master\AppData\Local\Temp\arduino_build_706859\sketch\music.ino.cpp" -o "nul"
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src" "C:\Users\Master\Documents\Arduino\libraries\SD\src\File.cpp" -o "nul"
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src" "C:\Users\Master\Documents\Arduino\libraries\SD\src\SD.cpp" -o "nul"
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src" "C:\Users\Master\Documents\Arduino\libraries\SD\src\utility\Sd2Card.cpp" -o "nul"
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src" "C:\Users\Master\Documents\Arduino\libraries\SD\src\utility\SdFile.cpp" -o "nul"
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src" "C:\Users\Master\Documents\Arduino\libraries\SD\src\utility\SdVolume.cpp" -o "nul"
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src" "C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp" -o "nul"
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src" "C:\Users\Master\Documents\Arduino\libraries\TMRpcm\pcmRF.cpp" -o "nul"
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src" "C:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src\SPI.cpp" -o "nul"
Generating function prototypes...
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -w -x c++ -E -CC -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src" "C:\Users\Master\AppData\Local\Temp\arduino_build_706859\sketch\music.ino.cpp" -o "C:\Users\Master\AppData\Local\Temp\arduino_build_706859\preproc\ctags_target_for_gcc_minus_e.cpp"
"D:\Arduino\tools-builder\ctags\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\Users\Master\AppData\Local\Temp\arduino_build_706859\preproc\ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src" "C:\Users\Master\AppData\Local\Temp\arduino_build_706859\sketch\music.ino.cpp" -o "C:\Users\Master\AppData\Local\Temp\arduino_build_706859\sketch\music.ino.cpp.o"
Compiling libraries...
Compiling library "SD"
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src" "C:\Users\Master\Documents\Arduino\libraries\SD\src\File.cpp" -o "C:\Users\Master\AppData\Local\Temp\arduino_build_706859\libraries\SD\File.cpp.o"
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src" "C:\Users\Master\Documents\Arduino\libraries\SD\src\SD.cpp" -o "C:\Users\Master\AppData\Local\Temp\arduino_build_706859\libraries\SD\SD.cpp.o"
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src" "C:\Users\Master\Documents\Arduino\libraries\SD\src\utility\Sd2Card.cpp" -o "C:\Users\Master\AppData\Local\Temp\arduino_build_706859\libraries\SD\utility\Sd2Card.cpp.o"
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src" "C:\Users\Master\Documents\Arduino\libraries\SD\src\utility\SdFile.cpp" -o "C:\Users\Master\AppData\Local\Temp\arduino_build_706859\libraries\SD\utility\SdFile.cpp.o"
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src" "C:\Users\Master\Documents\Arduino\libraries\SD\src\utility\SdVolume.cpp" -o "C:\Users\Master\AppData\Local\Temp\arduino_build_706859\libraries\SD\utility\SdVolume.cpp.o"
Compiling library "TMRpcm"
"D:\Arduino\hardware\tools\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega32 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_AVR_ATmega32 -DARDUINO_ARCH_AVR   "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\variants\standard" "-IC:\Users\Master\Documents\Arduino\libraries\SD\src" "-IC:\Users\Master\Documents\Arduino\libraries\TMRpcm" "-IC:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI\src" "C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp" -o "C:\Users\Master\AppData\Local\Temp\arduino_build_706859\libraries\TMRpcm\TMRpcm.cpp.o"
In file included from d:\arduino\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from d:\arduino\hardware\tools\avr\avr\include\avr\pgmspace.h:90,

                 from C:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles/Arduino.h:28,

                 from C:\Users\Master\Documents\Arduino\libraries\TMRpcm/pcmConfig.h:20,

                 from C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:4:

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:19:27: error: 'ICIE1' was not declared in this scope

  const byte togByte = _BV(ICIE1); //Get the value for toggling the buffer interrupt on/off

                           ^

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:102:18: error: expected unqualified-id before 'volatile'

   volatile byte *TIMSK[] = {&TIMSK1};

                  ^

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:102:18: error: expected ')' before 'volatile'

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:102:18: error: expected ')' before 'volatile'

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:102:18: error: expected initializer before 'volatile'

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp: In member function 'void TMRpcm::stopPlayback()':

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:372:11: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

  *TIMSK[tt] &= ~(togByte | _BV(TOIE1));

           ^

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp: In member function 'void TMRpcm::pause()':

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:392:13: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

    *TIMSK[tt] |= ( _BV(ICIE1) | _BV(TOIE1) );

             ^

In file included from d:\arduino\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from d:\arduino\hardware\tools\avr\avr\include\avr\pgmspace.h:90,

                 from C:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\cores\MCUdude_corefiles/Arduino.h:28,

                 from C:\Users\Master\Documents\Arduino\libraries\TMRpcm/pcmConfig.h:20,

                 from C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:4:

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:392:24: error: 'ICIE1' was not declared in this scope

    *TIMSK[tt] |= ( _BV(ICIE1) | _BV(TOIE1) );

                        ^

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:398:12: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

   *TIMSK[tt] &= ~( _BV(TOIE1) );

            ^

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp: In member function 'void TMRpcm::play(char*, long unsigned int)':

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:539:14: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

     *TIMSK[tt] = ( togByte | _BV(TOIE1) );

              ^

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp: In function 'void __vector_6()':

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:588:12: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

   *TIMSK[tt] &= ~togByte;

            ^

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:594:59: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

       if(bitRead(optionByte,3)){ sFile.seek(44); *TIMSK[tt] |= togByte; return;}

                                                           ^

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:595:16: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

       *TIMSK[tt] &= ~( togByte | _BV(TOIE1) );

                ^

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:607:13: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

    *TIMSK[tt] |= togByte;

             ^

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp: In member function 'void TMRpcm::disable()':

C:\Users\Master\Documents\Arduino\libraries\TMRpcm\TMRpcm.cpp:709:11: error: invalid types 'volatile uint8_t {aka volatile unsigned char}[byte {aka unsigned char}]' for array subscript

  *TIMSK[tt] &= ~( togByte | _BV(TOIE1) );

           ^

Multiple libraries were found for "SD.h"
 Used: C:\Users\Master\Documents\Arduino\libraries\SD
 Not used: C:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SD
 Not used: D:\Arduino\libraries\SD
Using library SD at version 1.2.2 in folder: C:\Users\Master\Documents\Arduino\libraries\SD 
Using library TMRpcm at version 1.0 in folder: C:\Users\Master\Documents\Arduino\libraries\TMRpcm 
Using library SPI at version 1.0 in folder: C:\Users\Master\AppData\Local\Arduino15\packages\MightyCore\hardware\avr\2.0.1\libraries\SPI 
exit status 1
Error compiling for board ATmega32.`

**Comment by TMRh20** [comment]
ATmega32 is not supported
