### ISSUE TITLE
Loud noisy peep sounds before, during and after .wav plays

### ISSUE THREAD

**Issue by benthek** [TMRh20/TMRpcm#89]
Hi! 
When I am trying to play a .wav file using this library, an Arduino Uno, SD card reader, PAM8403 amplifier and 8 Ohm speaker, I always get a very loud noise peep sound. 

I tried a lot of things but still can't figure it out;

- The sound is fine when I connect my iPhone with Audio jack, so speakers, amplifier, soldering and wiring should be OK right?
- It doesn't change when I power my Arduino with 9V battery, so it doesn't seem like a powering issue
- I tested with a .wav file from another Github user, and it makes no difference so it doesn't seem to be the file itself
- However I also tested with all the possible sample rates, tried both iTunes as Audacity for converting..

Still that annoying beep, so loud I can hardly hear the audio file itself.

Any suggestions of things I am missing?

```
#include <SD.h>
#include <TMRpcm.h>
#include <SPI.h>
const int SD_CARD = 4;

TMRpcm audio;

void setup() {
  audio.speakerPin = 9;
  digitalWrite(audio.speakerPin, LOW);
  Serial.begin(9600);

  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }

  // Tried from 3 to 7, no difference
  audio.setVolume(5);
  
  // Tried both 1 and 0 for quality
  audio.quality(0);

  delay(1000);
  
  Serial.print("Initializing SD card...");

  if (!SD.begin(SD_CARD)) {
    Serial.println("Card failed, or not present");
    return;
  }
  Serial.println("card initialized.");
}

void loop() {
 File mp3File = SD.open("test.wav");

  delay(100);

  if (!mp3File) {
    Serial.println("error opening test.wav");
    while (true);
  }
  
  audio.play("test.wav");
}

```

Thanks!

**Comment by Neo1975** [comment]
Hi, did you solved?
